### ISSUE TITLE
mixin nav > ul > li > a

### ISSUE THREAD

**Issue by theskillwithin** [DevTips/DevTips-Starter-Kit#11]
I wonder would it be possible to write a mixin that takes the hassle out of turning a list into a menu with links in it.  I do this on every projects because every project has a menu.

**Comment by timbog80** [comment]
you can do this with emmet. 

```nav>ul>li*5>a[path_to_link.html]{link$$}```
and press tab:

```<nav>
  <ul>
    <li><a href="path_to_link.html">link01</a></li>
    <li><a href="path_to_link.html">link02</a></li>
    <li><a href="path_to_link.html">link03</a></li>
    <li><a href="path_to_link.html">link04</a></li>
    <li><a href="path_to_link.html">link05</a></li>
  </ul>
</nav>```

**Comment by theskillwithin** [comment]
I'm talking about styling it not html.

**Comment by timbog80** [comment]
i dont think there is any way its not hard if you use sass:

```
nav
  ul
  
  li

  a

**Comment by theskillwithin** [comment]
of course there is a way, you just create a mixin that gives it the properties that you would normally input when you write a menu. list style type none, etc etc

**Comment by travisneilson** [comment]
I saw your PR, thanks for submitting. I am not going to be accepting it, however, as it's outside the scope of what I want this repo to be. Thank you so much for your interest!
